src/Entity/User.php
<?php declare(strict_types = 1);
/**
 * Created by PhpStorm.
 * User: nicolas
 * Date: 12/07/18
 * Time: 16:48
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\UuidInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity
 * @ORM\Table(name="user")
 */
class User implements UserInterface
{
    /**
     * @var UuidInterface
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\Column(name="uuid", type="uuid", unique=true)
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     */
    private UuidInterface $uuid;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private string $firstName;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private string $lastName;

    /**
     * @var array
     * @ORM\Column(type="array")
     */
    private array $roles;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private string $password;

    /**
     * @var string|null
     */
    private ?string $plainPassword;

    /**
     * @var string|null
     * @ORM\Column(type="string", nullable=true)
     */
    private ?string $salt;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private string $username;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private string $email;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity=Interest::class, mappedBy="project")
     */
    private Collection $interests;

    /**
     * User constructor.
     */
    public function __construct()
    {
        $this->interests = new ArrayCollection();
        $this->plainPassword = null;
        $this->roles = ['ROLE_USER'];
        $this->salt = null;
    }

    /**
     * @return UuidInterface
     */
    public function getUuid(): UuidInterface
    {
        return $this->uuid;
    }

    /**
     * @param UuidInterface $uuid
     * @return User
     */
    public function setUuid(UuidInterface $uuid): User
    {
        $this->uuid = $uuid;
        return $this;
    }

    /**
     * @return string
     */
    public function getFirstName(): string
    {
        return $this->firstName;
    }

    /**
     * @param string $firstName
     *
     * @return User
     */
    public function setFirstName(string $firstName): User
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * @return string
     */
    public function getLastName(): string
    {
        return $this->lastName;
    }

    /**
     * @return string
     */
    public function getFullName(): string
    {
        return $this->firstName.' '.$this->lastName;
    }

    /**
     * @param string $lastName
     *
     * @return User
     */
    public function setLastName(string $lastName): User
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     *
     * @return string[] The user roles
     */
    public function getRoles(): array
    {
        return $this->roles;
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string The password
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt(): ?string
    {
        return $this->salt;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername(): string
    {
        return $this->username;
    }

    /**
     * @param array $roles
     *
     * @return User
     */
    public function setRoles(array $roles): User
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @param string $role
     *
     * @return User
     */
    public function addRoles(string $role): User
    {
        if (!\in_array($role, $this->roles, true)) {
            $this->roles[] = $role;
        }

        return $this;
    }

    /**
     * @param string $password
     *
     * @return User
     */
    public function setPassword(string $password): User
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return string
     */
    public function getPlainPassword(): string
    {
        return $this->plainPassword;
    }

    /**
     * @param string $plainPassword
     *
     * @return User
     */
    public function setPlainPassword(string $plainPassword): User
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    /**
     * @param string|null $salt
     *
     * @return User
     */
    public function setSalt(?string $salt): User
    {
        $this->salt = $salt;

        return $this;
    }

    /**
     * @return string
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * @param string $email
     *
     * @return User
     */
    public function setEmail(string $email): User
    {
        // email will be our username
        $this->username = $email;
        $this->email = $email;

        return $this;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials(): void
    {
        $this->plainPassword = null;
    }

    /**
     * @return Collection
     */
    public function getInterests()
    {
        return $this->interests;
    }

    /**
     * @param Collection $interests
     * @return Project
     */
    public function setInterests(Collection $interests)
    {
        $this->interests = $interests;
        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <title>{% block title %}Mon test Anaxago{% endblock %}</title>
    {% block stylesheets %}{% endblock %}
    <link rel="icon" type="image/x-icon" href="favicon.ico"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdn.materialdesignicons.com/5.4.55/css/materialdesignicons.min.css">
</head>
<body>
{% block header %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ path('anaxago_starter_homepage') }}">
                <img src="https://www.anaxago.com/bundles/satoripopfront/img/logo.svg" height="40" class="d-inline-block align-top" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="nav justify-content-end w-100">
                    {% if not app.user %}
                        <li><a href="{{ path('anaxago_starter_login') }}" class="btn btn-outline-success my-2 my-sm-0">Se connecter</a>
                        </li>
                        <li><a href="{{ path('anaxago_starter_registration') }}" class="btn btn-outline-primary my-2 my-sm-0 ml-2">S'enregistrer</a></li>
                    {% else %}
                        <li><p>Bonjour {{ app.user.fullName }}</p></li>
                        <li><a class="btn btn-outline-success my-2 my-sm-0 ml-2 btn-sm" href="{{ path("anaxago_starter_myinterests") }}">Mes marques d'intérêts</a></li>
                        <li><a class="btn btn-outline-danger my-2 my-sm-0 ml-2 btn-sm" href="{{ path('app_logout') }}">Déconnexion</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}
<div class="container">
    {% block body %}
    {% endblock %}
</div>
{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
{% endblock %}
</body>
</html>

templates/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}
        <form class="mt-5" method="post">
            <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
            <div class="form-group">
                <label for="email">Email :</label>
                <input  class="form-control" placeholder="Saisissez votre adresse email"
                        type="text" value="{{ last_username }}" name="email" id="inputEmail" />
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input  class="form-control" placeholder="Saisissez votre mot de passe"
                        type="password" name="password" id="inputPassword" required/>
            </div>
            <button class="btn btn-outline-success w-100" type="submit">Se connecter</button>
        </form>
{% endblock %}

templates/registration.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Inscription</h1>
    {{ form_start(form) }}
    {{ form_row(form) }}
    <button class="btn btn-outline-success w-100" type="submit">S'inscrire</button>
    {{ form_end(form) }}
{% endblock %}